#!/usr/bin/env bash

CONFIG_FILE="/etc/greetd/config.toml"

if [ ! -f "$CONFIG_FILE" ]; then
    echo "$CONFIG_FILE not found."
    exit 1
fi

sed -i '/^\[default_session\]/,/^\[/ s|^\( *command = \).*|\1"Hyprland --config /etc/greetd/hyprland.conf"|' "$CONFIG_FILE"

