#!/usr/bin/env bash

CONFIG_FILE="/etc/greetd/config.toml"

if [ ! -f "$CONFIG_FILE" ]; then
    echo "❌ Error: $CONFIG_FILE not found."
    exit 1
fi

sed -i "/^\[terminal\]/,/^\[/ s|^\( *command = \).*|\1\"qtgreet --cmd '{{ command }}'\"|" "$CONFIG_FILE"

sed -i '/^\[default_session\]/,/^\[/ s|^\( *command = \).*|\1"dbus-run-session Hyprland"|' "$CONFIG_FILE"
